services:
  - type: web
    name: crop-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run_all_servers.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
